# Generated by Django 4.1.4 on 2022-12-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(verbose_name='meal date'),
        ),
        migrations.AlterField(
            model_name='food',
            name='enjoyedMeal',
            field=models.CharField(choices=[('Y', 'They enjoyed the meal'), ('N', 'They did not enjoy the meal')], default='N', max_length=1),
        ),
    ]
